#  load SemOpenAlex triples inside GraphDB

services:
  graphdb:
    container_name: graphdb-preload
    image: ontotext/graphdb:11.1.3
    mem_limit: 110g
    mem_reservation: 110g

    entrypoint: [ "/opt/graphdb/dist/bin/importrdf",
                  "preload", 
                  "--chunk", "20m", "--force",
                  "--recursive", "--parsing-tasks", "24",
                  "--recovery-point-interval", "3600",
                  "--id", "semopenalex",
                  "/opt/graphdb/graphdb-import/" ]

    environment:
      GDB_JAVA_OPTS: >-
        -Xms90g
        -Xmx90g
        -Dgraphdb.home=/opt/graphdb/home
        -Dgraphdb.workbench.importDirectory=/opt/graphdb/graphdb-import

    volumes:
      - /data/graphdb-home:/opt/graphdb/home:Z
      - /data/graphdb-import-semopenalex:/opt/graphdb/graphdb-import:Z
